<a href="https://colab.research.google.com/github/PHAMVANTU467/TH-DEEP-LEARNING/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
pip install numpy

In [ ]:
import numpy as np

my_list = [1,9,10,15]
print('Python list: ',my_list)

my_numpy_array = np.array(my_list)
print('Numpy array: ',my_numpy_array)


a = np.array([1,2,3,4,5])
print(a)

ad = np.array([1,2,3,4,5])


b = np.array([(1,2,3),(4,5,6)])
print(b)

c = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(c)


print('Lam phang du lieu')
temp = c.flatten()
print(temp)

reshap_test = b.reshape(3,2)
print(reshap_test)

print('Them dong du lieu')
h_stack = np.hstack((a,ad))
print(h_stack)

v_stack = np.vstack((a,ad))
print(v_stack)

print('Sinh mang ngau nhien')
test_a = np.random.randint(100,size=(10,))
print('Mang 1 chieu: ',test_a)
test_b = np.random.randint(100,size=(3,4))
print('Mang 2 chieu: ',test_b)

print('Sinh mang ngau nhien so thuc')
test_c = np.random.uniform(50,100,size = 10)
print(test_c)

print('Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian')
diem_thi= np.random.normal(loc=8,scale=1,size=6)
print(diem_thi)

In [36]:
import numpy as np
def check0(x):
  if x > 0:
    return 1
  else:
    return 0


print('Bai Tap 1')
bai1 = np.random.randint(0,20,(3,3))
print(bai1)

for i in range(len(bai1)):
  for j in range(len(bai1[i])):
    if check0(bai1[i][j]) == 1:
      print('Khong co phan tu nho hon 0')
    else:
      print('Co phan tu nho hon 0')

# Kiểm tra: "Tất cả phần tử có > 0 không?"
if (bai1 > 0).all():
    print('Khong co phan tu nho hon hoac bang 0')
else:
    print('Co phan tu nho hon hoac bang 0')

Bai Tap 1
[[14  9  9]
 [10  3  5]
 [ 0  2 14]]
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Co phan tu nho hon 0
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Co phan tu nho hon hoac bang 0


In [ ]:
import numpy as np

def bai1():
    a = np.random.randint(0, 21, (3,3))
    print("Mảng:\n", a)
    print("Tất cả phần tử khác 0:", np.all(a != 0))

def bai2():
    a = np.random.randint(0, 21, (3,3))
    print("Mảng:\n", a)
    print("Tồn tại phần tử khác 0:", np.any(a != 0))

def bai3():
    a = np.array([1, 2, 3])
    b = np.array([2, 2, 1])
    print("a:", a)
    print("b:", b)
    print("greater:", np.greater(a, b))
    print("greater_equal:", np.greater_equal(a, b))
    print("less:", np.less(a, b))
    print("less_equal:", np.less_equal(a, b))

def bai4():
    a = np.array([1]*10 + [0]*10 + [5]*10)
    print(a)

def bai5():
    a = np.arange(30, 71)
    a = a[a % 2 == 0]
    print(a)

def bai6():
    a = np.identity(3)
    print(a)

def bai7():
    a = np.random.randint(15, 56, 10)
    print("Mảng:", a)
    print("Giá trị bỏ đầu và cuối:", a[1:-1])

def bai8():
    a = np.random.randint(0, 21, 20)
    print("Mảng ban đầu:", a)
    a[(a >= 9) & (a <= 15)] *= -1
    print("Sau khi đổi dấu:", a)

def bai9():
    a = np.random.randint(10, 22, (3,4))
    print(a)

def bai10():
    a = np.ones((10,10))
    a[1:-1,1:-1] = 0
    print(a)

def bai11():
    a = np.diag([1,2,3,4,5])
    print(a)

def bai12():
    a = np.random.randint(0, 10, (3,3,3))
    print("Mảng 3x3x3:\n", a)
    print("Tổng theo dòng:", np.sum(a, axis=1))
    print("Tổng theo cột:", np.sum(a, axis=2))

# MENU
while True:
    print("\n===== MENU =====")
    print("1. all != 0")
    print("2. any != 0")
    print("3. So sánh mảng")
    print("4. Tạo mảng 1,0,5")
    print("5. Số chẵn [30,70]")
    print("6. Ma trận đơn vị")
    print("7. Bỏ phần tử đầu cuối")
    print("8. Đổi dấu [9,15]")
    print("9. Ma trận 3x4")
    print("10. Ma trận viền 1")
    print("11. Ma trận diag")
    print("12. Mảng 3x3x3 + sum")
    print("0. Thoát")

    choice = input("Chọn: ")

    if choice == "1": bai1()
    elif choice == "2": bai2()
    elif choice == "3": bai3()
    elif choice == "4": bai4()
    elif choice == "5": bai5()
    elif choice == "6": bai6()
    elif choice == "7": bai7()
    elif choice == "8": bai8()
    elif choice == "9": bai9()
    elif choice == "10": bai10()
    elif choice == "11": bai11()
    elif choice == "12": bai12()
    elif choice == "0": break
    else:
        print("Chọn sai!")