<a href="https://colab.research.google.com/github/PHAMVANTU467/TH-DEEP-LEARNING/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
pip install numpy

In [ ]:
import numpy as np

my_list = [1,9,10,15]
print('Python list: ',my_list)

my_numpy_array = np.array(my_list)
print('Numpy array: ',my_numpy_array)


a = np.array([1,2,3,4,5])
print(a)

ad = np.array([1,2,3,4,5])


b = np.array([(1,2,3),(4,5,6)])
print(b)

c = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(c)


print('Lam phang du lieu')
temp = c.flatten()
print(temp)

reshap_test = b.reshape(3,2)
print(reshap_test)

print('Them dong du lieu')
h_stack = np.hstack((a,ad))
print(h_stack)

v_stack = np.vstack((a,ad))
print(v_stack)

print('Sinh mang ngau nhien')
test_a = np.random.randint(100,size=(10,))
print('Mang 1 chieu: ',test_a)
test_b = np.random.randint(100,size=(3,4))
print('Mang 2 chieu: ',test_b)

print('Sinh mang ngau nhien so thuc')
test_c = np.random.uniform(50,100,size = 10)
print(test_c)

print('Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian')
diem_thi= np.random.normal(loc=8,scale=1,size=6)
print(diem_thi)

In [36]:
import numpy as np
def check0(x):
  if x > 0:
    return 1
  else:
    return 0


print('Bai Tap 1')
bai1 = np.random.randint(0,20,(3,3))
print(bai1)

for i in range(len(bai1)):
  for j in range(len(bai1[i])):
    if check0(bai1[i][j]) == 1:
      print('Khong co phan tu nho hon 0')
    else:
      print('Co phan tu nho hon 0')

# Kiểm tra: "Tất cả phần tử có > 0 không?"
if (bai1 > 0).all():
    print('Khong co phan tu nho hon hoac bang 0')
else:
    print('Co phan tu nho hon hoac bang 0')

Bai Tap 1
[[14  9  9]
 [10  3  5]
 [ 0  2 14]]
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Co phan tu nho hon 0
Khong co phan tu nho hon 0
Khong co phan tu nho hon 0
Co phan tu nho hon hoac bang 0


In [ ]:
import numpy as np

def bai1():
    a = np.random.randint(0, 21, (3,3))
    print("Mảng:\n", a)
    print("Tất cả phần tử khác 0:", np.all(a != 0))

def bai2():
    a = np.random.randint(0, 21, (3,3))
    print("Mảng:\n", a)
    print("Tồn tại phần tử khác 0:", np.any(a != 0))

def bai3():
    a = np.array([1, 2, 3])
    b = np.array([2, 2, 1])
    print("a:", a)
    print("b:", b)
    print("greater:", np.greater(a, b))
    print("greater_equal:", np.greater_equal(a, b))
    print("less:", np.less(a, b))
    print("less_equal:", np.less_equal(a, b))

def bai4():
    a = np.array([1]*10 + [0]*10 + [5]*10)
    print(a)

def bai5():
    a = np.arange(30, 71)
    a = a[a % 2 == 0]
    print(a)

def bai6():
    a = np.identity(3)
    print(a)

def bai7():
    a = np.random.randint(15, 56, 10)
    print("Mảng:", a)
    print("Giá trị bỏ đầu và cuối:", a[1:-1])

def bai8():
    a = np.random.randint(0, 21, 20)
    print("Mảng ban đầu:", a)
    a[(a >= 9) & (a <= 15)] *= -1
    print("Sau khi đổi dấu:", a)

def bai9():
    a = np.random.randint(10, 22, (3,4))
    print(a)

def bai10():
    a = np.ones((10,10))
    a[1:-1,1:-1] = 0
    print(a)

def bai11():
    a = np.diag([1,2,3,4,5])
    print(a)

def bai12():
    a = np.random.randint(0, 10, (3,3,3))
    print("Mảng 3x3x3:\n", a)
    print("Tổng theo dòng:", np.sum(a, axis=1))
    print("Tổng theo cột:", np.sum(a, axis=2))

# MENU
while True:
    print("\n===== MENU =====")
    print("1. all != 0")
    print("2. any != 0")
    print("3. So sánh mảng")
    print("4. Tạo mảng 1,0,5")
    print("5. Số chẵn [30,70]")
    print("6. Ma trận đơn vị")
    print("7. Bỏ phần tử đầu cuối")
    print("8. Đổi dấu [9,15]")
    print("9. Ma trận 3x4")
    print("10. Ma trận viền 1")
    print("11. Ma trận diag")
    print("12. Mảng 3x3x3 + sum")
    print("0. Thoát")

    choice = input("Chọn: ")

    if choice == "1": bai1()
    elif choice == "2": bai2()
    elif choice == "3": bai3()
    elif choice == "4": bai4()
    elif choice == "5": bai5()
    elif choice == "6": bai6()
    elif choice == "7": bai7()
    elif choice == "8": bai8()
    elif choice == "9": bai9()
    elif choice == "10": bai10()
    elif choice == "11": bai11()
    elif choice == "12": bai12()
    elif choice == "0": break
    else:
        print("Chọn sai!")

In [42]:
Bai_2 = np.random.randint(0,20,size=(3,3))
print(Bai_2)
if np.any(Bai_2!=0) == True:
  print('Ton tai phan tu khac 0')
else:
  print('Khong ton tai phan tu khac 0')

if np.all(Bai_2!=0)==True:
  print('Tat ca cac phan tu trong mang khac 0')
else:
  print('Co phan tu trong mang la 0')

[[ 3 12 10]
 [ 4 11 19]
 [ 9 11  8]]
Ton tai phan tu khac 0
Tat ca cac phan tu trong mang khac 0


In [49]:
array_1 = [1,2,3,5,6,3,2]
array_2 = [4,5,6,3,6,2,9]
array_3 = np.random.randint(0,10,(3,3))
array_4 = np.random.randint(0,10,(3,3))

print('So sanh lon hon: ',np.greater(array_1,array_2))
print('Lon hon hoac bang: ',np.greater_equal(array_1,array_2))
print('Be hon: ',np.less(array_1,array_2))
print('Be hon hoac bang',np.less_equal(array_1,array_2))


print('So sanh lon hon: ',np.greater(array_3,array_4))
print('Lon hon hoac bang: ',np.greater_equal(array_3,array_4))
print('Be hon: ',np.less(array_3,array_4))
print('Be hon hoac bang',np.less_equal(array_3,array_4))

So sanh lon hon:  [False False False  True False  True False]
Lon hon hoac bang:  [False False False  True  True  True False]
Be hon:  [ True  True  True False False False  True]
Be hon hoac bang [ True  True  True False  True False  True]
So sanh lon hon:  [[False  True  True]
 [False False  True]
 [ True False False]]
Lon hon hoac bang:  [[False  True  True]
 [False False  True]
 [ True False False]]
Be hon:  [[ True False False]
 [ True  True False]
 [False  True  True]]
Be hon hoac bang [[ True False False]
 [ True  True False]
 [False  True  True]]


In [54]:
bai5_1=np.full(10,1)
bai5_2=np.full(10,0)
bai5_3=np.full(10,5)

temp1 = np.full((2,3),5)
temp2 = np.full((2,3),1)
temp3 = np.full((2,3),0)

print(bai5_1,bai5_2,bai5_3)
print(temp1,'\n',temp2,'\n',temp3)

[1 1 1 1 1 1 1 1 1 1] [0 0 0 0 0 0 0 0 0 0] [5 5 5 5 5 5 5 5 5 5]
[[5 5 5]
 [5 5 5]] 
 [[1 1 1]
 [1 1 1]] 
 [[0 0 0]
 [0 0 0]]


In [57]:
bai5 = np.arange(30,71,2)
print(bai5)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [58]:
bai6 = np.identity(3)
print(bai6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [66]:
bai7 = np.arange(15,55)
print(bai7[1:])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [68]:
bai8 = np.arange(0,20)
print(bai8)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
